###################################################################################################
# This script computes penalized phylogenetic informativeness and does various things with it
# Was used to produce results for Bellot et al. 2019. Scientific Reports
# Probably not ready-to-use by someone else but feel free to try
# Originally written by Sidonie BELLOT - RBG Kew - s.bellot@kew.org
# Use and modify as you wish, but please don't hesitate to give feedback!
####################################################################################################


require(gplots)
#require(heatmap.plus)


#Here, set the file name of the table generated by get_seq_lengths.py
sample.filename = ""


allT <- read.table(sample.filename,header=T, row.names=NULL, sep="\t", stringsAsFactors = F)



### Compute penalized PI

# make new column and populate it with the PI value at Tmax for each locus

allT$PI_at_Tmax <- rep(0,length(allT$Locus))

for (x in (1:length(allT$Locus))) {
  tmax <- allT$Tmax[x]
  PI_tmax <- allT[x,tmax]
  allT$PI_at_Tmax[x] <- PI_tmax
}

# remove loci where PI at Tmax is inferior to PI at T0.006 (genes with phanthom peaks)

allT_noGosts <- allT[!(allT$PI_at_Tmax <= allT$Time_0.006),]
allT <- allT_noGosts

# make a new pen column for each epoch

allT$PIpen_E0.05_0.25 <- rep(0,length(allT$Locus))
allT$PIpen_E0.25_0.4 <- rep(0,length(allT$Locus))
allT$PIpen_E0.4_0.7 <- rep(0,length(allT$Locus))
allT$PIpen_E0.7_1 <- rep(0,length(allT$Locus))

# for each epoch, for each locus, if tmax < Te, calculate penalized PI (penPI = PI*(PI at Te / PI at Tmax)), else use original PI
# with an effort could loop through epochs, but will do it one by one

# E0_0.25

for (x in (1:length(allT$Locus))) {
  tmax <- as.numeric(strsplit(allT$Tmax[x], "_")[[1]][2])
  te <- 0.15
  if (tmax < te) {
    PI <- allT$Epoch0.05_0.25[x]
    PI_te <- allT$T0.15[x]
    PI_tmax <- allT$PI_at_Tmax[x]
    penPI <- PI*(PI_te/PI_tmax)
  } else {
  penPI <- allT$Epoch0.05_0.25[x]
  }
  allT$PIpen_E0.05_0.25[x] <- penPI
}


# E0.2_0.4

for (x in (1:length(allT$Locus))) {
  tmax <- as.numeric(strsplit(allT$Tmax[x], "_")[[1]][2])
  te <- 0.325
  if (tmax < te) {
    PI <- allT$Epoch0.25_0.4[x]
    PI_te <- allT$T0.325[x]
    PI_tmax <- allT$PI_at_Tmax[x]
    penPI <- PI*(PI_te/PI_tmax)
  } else {
    penPI <- allT$Epoch0.25_0.4[x]
  }
  allT$PIpen_E0.25_0.4[x] <- penPI
}



# E0.4_0.7

for (x in (1:length(allT$Locus))) {
  tmax <- as.numeric(strsplit(allT$Tmax[x], "_")[[1]][2])
  te <- 0.55
  if (tmax < te) {
    PI <- allT$Epoch0.4_0.7[x]
    PI_te <- allT$T0.55[x]
    PI_tmax <- allT$PI_at_Tmax[x]
    penPI <- PI*(PI_te/PI_tmax)
  } else {
    penPI <- allT$Epoch0.4_0.7[x]
  }
  allT$PIpen_E0.4_0.7[x] <- penPI
}

head(allT)


# E0.7_1

for (x in (1:length(allT$Locus))) {
  tmax <- as.numeric(strsplit(allT$Tmax[x], "_")[[1]][2])
  te <- 0.85
  if (tmax < te) {
    PI <- allT$Epoch0.7_1[x]
    PI_te <- allT$T0.85[x]
    PI_tmax <- allT$PI_at_Tmax[x]
    penPI <- PI*(PI_te/PI_tmax)
  } else {
    penPI <- allT$Epoch0.7_1[x]
  }
  allT$PIpen_E0.7_1[x] <- penPI
}

head(allT)




# Create a table with only useful columns

allT_reduced <- allT[, c(1:11, 13, 15, 17, 19, 125:128)]
head(allT_reduced)

write.table(allT_reduced, file="allTaxa_reduced", sep="\t", row.names = F)

# Create histograms to see how informative are genes


ggplot(allT_reduced, aes(x=Taxa, fill=Category2, color=Category2)) + 
  geom_histogram(binwidth=1, position="identity", alpha=0.5) +
  scale_color_grey()+scale_fill_grey() +
  theme_classic()


ggplot(allT_reduced, aes(x=Sites, fill=Category2, color=Category2)) + 
  geom_histogram(binwidth=100, position="identity", alpha=0.5) +
  scale_color_grey()+scale_fill_grey() +
  theme_classic()

ggplot(allT_reduced, aes(x=Mean_rate, fill=Category2, color=Category2)) + 
  geom_histogram(position="identity", alpha=0.5) +
  scale_color_grey()+scale_fill_grey() +
  theme_classic()

ggplot(allT_reduced, aes(x=Percent_Above_70, fill=Category2, color=Category2)) + 
  geom_histogram(binwidth=10, position="identity", alpha=0.5) +
  scale_color_grey()+scale_fill_grey() +
  theme_classic()

ggplot(allT_reduced, aes(x=Optimal_sites, fill=Category2, color=Category2)) + 
  geom_histogram(binwidth=100, position="identity", alpha=0.5) +
  scale_color_grey()+scale_fill_grey() +
  theme_classic()

ggplot(allT_reduced, aes(x=Weighted_optimal_sites, fill=Category2, color=Category2)) + 
  geom_histogram(binwidth=100, position="identity", alpha=0.5) +
  scale_color_grey()+scale_fill_grey() +
  theme_classic()

ggplot(allT_reduced, aes(x=allT_reduced$PIpen_E0.7_1, fill=Category2, color=Category2)) + 
  geom_histogram(position="identity", alpha=0.5) +
  scale_color_grey()+scale_fill_grey() +
  theme_classic()


# create plots of PI and penPI for all genes

# df1 <- allT_reduced[, c(1,11,16)]
# df1$Epoch <- rep("e1", length(df1$Locus))
# colnames(df1)[2] <- "PI"
# colnames(df1)[3] <- "penPI"
# 
# df2 <- allT_reduced[, c(1,12,17)]
# df2$Epoch <- rep("e2", length(df2$Locus))
# colnames(df2)[2] <- "PI"
# colnames(df2)[3] <- "penPI"
# 
# df3 <- allT_reduced[, c(1,13,18)]
# df3$Epoch <- rep("e3", length(df3$Locus))
# colnames(df3)[2] <- "PI"
# colnames(df3)[3] <- "penPI"
# 
# df4 <- allT_reduced[, c(1,14,19)]
# df4$Epoch <- rep("e4", length(df4$Locus))
# colnames(df4)[2] <- "PI"
# colnames(df4)[3] <- "penPI"

df1 <- allT_reduced[, c(1,11)]
df1$Epoch <- rep("e1", length(df1$Locus))
colnames(df1)[2] <- "PI"

df2 <- allT_reduced[, c(1,12)]
df2$Epoch <- rep("e2", length(df2$Locus))
colnames(df2)[2] <- "PI"

df3 <- allT_reduced[, c(1,13)]
df3$Epoch <- rep("e3", length(df3$Locus))
colnames(df3)[2] <- "PI"

df4 <- allT_reduced[, c(1,14)]
df4$Epoch <- rep("e4", length(df4$Locus))
colnames(df4)[2] <- "PI"

df5 <- allT_reduced[, c(1,16)]
df5$Epoch <- rep("e1_penalized", length(df5$Locus))
colnames(df5)[2] <- "PI"

df6 <- allT_reduced[, c(1,17)]
df6$Epoch <- rep("e2_penalized", length(df6$Locus))
colnames(df6)[2] <- "PI"

df7 <- allT_reduced[, c(1,18)]
df7$Epoch <- rep("e3_penalized", length(df7$Locus))
colnames(df7)[2] <- "PI"

df8 <- allT_reduced[, c(1,19)]
df8$Epoch <- rep("e4_penalized", length(df8$Locus))
colnames(df8)[2] <- "PI"

df9 <- rbind(df1, df2)
df10 <- rbind(df9, df3)
df11 <- rbind(df10, df4)
df12 <- rbind(df11, df5)
df13 <- rbind(df12, df6)
df14 <- rbind(df13, df7)
df <- rbind(df14, df8)

df$order = c(1:length(df$Locus))


p1 <- ggplot(df, aes(x=reorder(Locus, order), y=df$PI, group=Epoch)) + 
  geom_point(aes(shape=Epoch, color=Epoch)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size=5)) +
  labs(x = "Locus", y="Phylogenetic informativeness") +
  scale_shape_manual(values=c(1, 4, 1, 4, 1, 4, 1, 4))+
  scale_color_manual(values=c('red','red', 'orange', 'orange', 'blue', 'blue', 'green', 'green'))
  
pdf("Figure_PI_penPI_allT_overlap.pdf", 20, 6)
plot(p1)
dev.off()

# p2 <- ggplot(df, aes(x=reorder(Locus, order), y=df$penPI, fill=Epoch, color=Epoch)) + 
#   geom_point(size=0.8) +
#   theme(axis.text.x = element_text(angle = 90, hjust = 1, size=5)) +
#   labs(x = "Locus", y="Penalized phylogenetic informativeness")
# 
# pdf("Figure_PI_penPI_allT.pdf", 20, 12)
# plot_grid(p1, p2, ncol=1)
# dev.off()

# Create symetric rank tables, one with averages for ties (fractionized ranks), one with same minimum rank for ties (1224)
# This is more conservative because it will keep more genes at the highest ranks
# we will keep all the genes  that "deserve" to have one of the first 70 (25% of 277 ) ranks

allT_reduced_Franks <- allT_reduced

head(allT_reduced_Franks)

for (x in (5:length(colnames(allT_reduced)))) {
  allT_reduced_Franks[,x] <- rank(-allT_reduced[,x], ties.method = "average")   # the minus is to rank from largest to smallest
}

head(allT_reduced_Franks)


allT_reduced_Sranks <- allT_reduced

head(allT_reduced_Sranks)

for (x in (5:length(colnames(allT_reduced)))) {
  allT_reduced_Sranks[,x] <- rank(-allT_reduced[,x], ties.method = "max")   # the minus is to rank from largest to smallest
}

head(allT_reduced_Sranks)


# create a symetric table of the Sranks table with qualification as green/yellow/orange/red depending if rank 1-70, 71-139, 140-208, 209-277
# maybe useless

allT_reduced_Sranks_qual <- allT_reduced_Sranks

for (x in (5:length(colnames(allT_reduced_Sranks)))) {
  for (z in (1:length(allT_reduced_Sranks$Locus))) {
    if (allT_reduced_Sranks[z,x] <= 70) {allT_reduced_Sranks_qual[z,x] <- "green"} 
    else if (allT_reduced_Sranks[z,x] >70 & allT_reduced_Sranks[z,x] <= 139) {allT_reduced_Sranks_qual[z,x] <- "yellow"}
    else if (allT_reduced_Sranks[z,x] >139 & allT_reduced_Sranks[z,x] <= 208) {allT_reduced_Sranks_qual[z,x] <- "orange"}
    else if (allT_reduced_Sranks[z,x] > 208) {allT_reduced_Sranks_qual[z,x] <- "red"}
  }
}

head(allT_reduced_Sranks_qual)


# plot table Sranks with color depending on rank

pdf("AllTaxa_methods_heatmap_noGhosts.pdf")

allT_reduced_Sranks_red <- allT_reduced_Sranks[5:17]

x = 1:ncol(allT_reduced_Sranks_red)
y = 1:nrow(allT_reduced_Sranks_red)
centers <- expand.grid(y,x)

#make the plot margins a little bigger
par(mar = c(2,7,4,2))

image(x, y, t(allT_reduced_Sranks_red),
      col = c("green","yellow", "orange", "red"),
      breaks = c(0, 70, 139, 208, 277),
      xaxt = 'n', 
      yaxt = 'n', 
      xlab = '', 
      ylab = '',
      ylim = c(max(y) + 0.5, min(y) - 0.5)
)

#add margin text
mtext(colnames(allT_reduced_Sranks_red), at=1:ncol(allT_reduced_Sranks_red), padj = 0, cex=0.6, las=2)
mtext(allT_reduced_Sranks$Locus, at=1:nrow(allT_reduced_Sranks_red), side = 2, las = 1, adj = 1.2, cex=0.1)

#add black lines
#abline(h=y + 0.5)
#abline(v=x + 0.5)

dev.off()





# print list of promising genes depending on rank (change conditions as needed)

promising_v <- rep("", length(allT_reduced_Sranks$Locus))

for (z in (1:length(allT_reduced_Sranks$Locus))) {
  c <- 0
  taxa <- allT_reduced_Sranks$Taxa[z]
  #if (allT_reduced_Sranks$Weighted_optimal_sites[z] <= 70 & taxa >= 20) {promising_v[z] <- allT_reduced_Sranks$Locus[z]} else {promising_v[z] <- ""}
  for (x in (7:length(colnames(allT_reduced_Sranks)))) {
    if (allT_reduced_Sranks[z,x] <= 70) {c <- c + 1}
    if (c == 11 & taxa >= 0) {promising_v[z] <- allT_reduced_Sranks$Locus[z]} else {promising_v[z] <- ""}
  }
}

promising_v2 <- promising_v[promising_v != ""]

write(sort(promising_v2), "allTaxa_Promising_OPI70_T0.txt")



## OR select more explicitely promising genes depending on their performance in (a) given method(s):

# create new table with genes as good (1) or bad (0) depending on the method (MR >0.1 and <0.9, P70 > 80, WOS-OS > -5, penPI-PI > -5, allepochs good)

allT_reduced_Qual <- allT_reduced[, c(1:5, 6, 7, 9:13)]

head(allT_reduced_Qual)


  for (z in (1:length(allT_reduced_Qual$Locus))) {
    if (allT_reduced$Mean_rate[z] >= 0.1 & allT_reduced$Mean_rate[z] <= 0.9) {allT_reduced_Qual$Mean_rate[z] <- 1} else {allT_reduced_Qual$Mean_rate[z] <- 0}
    if (allT_reduced$Percent_Above_70[z] >= 80) {allT_reduced_Qual$Percent_Above_70[z] <- 1} else {allT_reduced_Qual$Percent_Above_70[z] <- 0}
    if (allT_reduced$Weighted_optimal_sites[z] - allT_reduced$Optimal_sites[z] >= -5 & allT_reduced$Weighted_optimal_sites[z] >= 100) {allT_reduced_Qual$Optimal_sites[z] <- 1} else {allT_reduced_Qual$Optimal_sites[z] <- 0}
    if (allT_reduced$PIpen_E0.05_0.25[z] - allT_reduced$Epoch0.05_0.25[z] >= -5 & allT_reduced$PIpen_E0.05_0.25[z] >= 5) {allT_reduced_Qual$Epoch0.05_0.25[z] <- 1} else {allT_reduced_Qual$Epoch0.05_0.25[z] <- 0}
    if (allT_reduced$PIpen_E0.25_0.4[z] - allT_reduced$Epoch0.25_0.4[z] >= -5 & allT_reduced$PIpen_E0.25_0.4[z] >= 5) {allT_reduced_Qual$Epoch0.25_0.4[z] <- 1} else {allT_reduced_Qual$Epoch0.25_0.4[z] <- 0}
    if (allT_reduced$PIpen_E0.4_0.7[z] - allT_reduced$Epoch0.4_0.7[z] >= -5 & allT_reduced$PIpen_E0.4_0.7[z] >= 5) {allT_reduced_Qual$Epoch0.4_0.7[z] <- 1} else {allT_reduced_Qual$Epoch0.4_0.7[z] <- 0}
    if (allT_reduced$PIpen_E0.7_1[z] - allT_reduced$Epoch0.7_1[z] >= -5 & allT_reduced$PIpen_E0.7_1[z] >= 5) {allT_reduced_Qual$Epoch0.7_1[z] <- 1} else {allT_reduced_Qual$Epoch0.7_1[z] <- 0}    
    if (sum(allT_reduced_Qual[z,8:11]) == 4) {allT_reduced_Qual$Epoch0.05_1[z] <- 1} else {allT_reduced_Qual$Epoch0.05_1[z] <- 0}
  }

# keep only loci good for all methods (or whatever we want)


#allT_reduced_Qual_good <- allT_reduced_Qual[!(allT_reduced_Qual$Percent_Above_70==0 & allT_reduced_Qual$Optimal_sites==0 & allT_reduced_Qual$Epoch0.05_0.25==0 &
 #                                             allT_reduced_Qual$Epoch0.25_0.4==0 & allT_reduced_Qual$Epoch0.4_0.7==0  & allT_reduced_Qual$Epoch0.7_1==0),]
#promising <- allT_reduced_Qual_AllGood$Locus


promising_v <- rep("", length(allT_reduced_Qual$Locus))

for (z in (1:length(allT_reduced_Qual$Locus))) {
  c <- 0
  taxa <- allT_reduced_Qual$Taxa[z]
  #if (allT_reduced_Sranks$Weighted_optimal_sites[z] <= 70 & taxa >= 20) {promising_v[z] <- allT_reduced_Sranks$Locus[z]} else {promising_v[z] <- ""}
  for (x in (7:length(colnames(allT_reduced_Qual))-5)) {
    if (allT_reduced_Qual[z,x] == 1) {c <- c + 1}
    if (c == 1 & taxa >= 0) {promising_v[z] <- allT_reduced_Qual$Locus[z]} else {promising_v[z] <- ""}
  }
}

promising_v2 <- promising_v[promising_v != ""]

write(sort(promising_v2), "allTaxa_Promising_OS1_T0.txt")



